name: Build & Push Docker Image

on:
  workflow_call:
    inputs:
      platforms:
        type: string
        default: linux/amd64,linux/arm64
    secrets:
      GHCR_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - id: meta
        run: echo "IMAGE=ghcr.io/${{ github.repository }}" >> "$GITHUB_ENV"

      - name: Build (no push)
        run: |
          docker buildx build \
            --platform ${{ inputs.platforms }} \
            -t $IMAGE:latest .

  push:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Tag & Push
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          [[ "$TAG" == "$GITHUB_REF" ]] && TAG=latest
          docker buildx build \
            --platform ${{ inputs.platforms }} \
            -t $IMAGE:$TAG \
            --push .